In [2]:
import pandas as pd
from googletrans import Translator as T
import time

In [34]:
# googletrans.__version__

In [35]:
"""
https://www.ostirion.net/post/translating-the-contents-of-excel-files-with-python
"""

'\nhttps://www.ostirion.net/post/translating-the-contents-of-excel-files-with-python\n'

## DF Preparation

In [3]:
table_pt = pd.read_excel(r'DataSets\insa_tca.xlsx', dtype=str)
table_pt.head(3)

,Unnamed: 0,Unnamed: 1,Grupo e subgrupos\n (Classificação FoodEx2 Níveis 1 a 3),Unnamed: 3,Unnamed: 4,Valores\npor 100 g de parte edível com exceção do grupo Bebidas alcoólicas (nível 1) cujos valores são expressos por 100 ml de parte edível,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44
0,Cod,Nome do alimento,Nível 1,Nível 2,Nivel 3,Energia\n[kcal],Energia\n[kJ],Lípidos\n[g],Ácidos gordos saturados\n[g],Ácidos gordos monoinsaturados \n[g],...,Vitamina C \n[mg],Folatos \n[µg],Cinza \n[g],Sódio \n[mg],Potássio \n[mg],Cálcio \n[mg],Fósforo \n[mg],Magnésio \n[mg],Ferro \n[mg],Zinco \n[mg]
1,624,Abacate,Frutos e produtos derivados de frutos,Fruta utilizada como fruta,"Frutos diversos com casca não comestível, grandes",114,470,10.5,2.2,6.5,...,3,11,0.75,15,330,4,36,21,0.3,0.3
2,625,Abóbora cristalizada,Produtos hortícolas e derivados,Produtos hortícolas transformados ou em conser...,Produtos hortícolas cristalizados ou conservad...,293,1240,0.2,0.1,0,...,0,0,0.15,27,22,28,2,3,0.4,0.1

In [5]:
col_name = table_pt.columns

In [7]:
for col in col_name:
    table_pt.rename(columns={col: table_pt[col][0].strip()}, inplace=True)

In [8]:
table_pt.drop([0], axis=0, inplace=True)

In [9]:
table_pt.head(3)

,Cod,Nome do alimento,Nível 1,Nível 2,Nivel 3,Energia\n[kcal],Energia\n[kJ],Lípidos\n[g],Ácidos gordos saturados\n[g],Ácidos gordos monoinsaturados \n[g],...,Vitamina C \n[mg],Folatos \n[µg],Cinza \n[g],Sódio \n[mg],Potássio \n[mg],Cálcio \n[mg],Fósforo \n[mg],Magnésio \n[mg],Ferro \n[mg],Zinco \n[mg]
1,624,Abacate,Frutos e produtos derivados de frutos,Fruta utilizada como fruta,"Frutos diversos com casca não comestível, grandes",114,470,10.5,2.2,6.5,...,3,11,0.75,15,330,4,36,21,0.3,0.3
2,625,Abóbora cristalizada,Produtos hortícolas e derivados,Produtos hortícolas transformados ou em conser...,Produtos hortícolas cristalizados ou conservad...,293,1240,0.2,0.1,0,...,0,0,0.15,27,22,28,2,3,0.4,0.1
3,579,Abóbora crua,Produtos hortícolas e derivados,Frutos de hortícolas,Frutos vegetais de cucurbitáceas,11,47,0.2,0.1,0,...,12,8,0.4,1,200,25,5,5,0.1,0.1

## Translator

In [41]:
table.columns

Index(['Cod', 'Nome do alimento', 'Nível 1', 'Nível 2', 'Nivel 3',
       'Energia\n[kcal]', 'Energia\n[kJ]', 'Lípidos\n[g]',
       'Ácidos gordos saturados\n[g]', 'Ácidos gordos monoinsaturados \n[g]',
       'Ácidos gordos polinsaturados \n[g]', 'Ácido linoleico \n[g]',
       'Ácidos gordos trans \n[g]', 'Hidratos de carbono \n[g]',
       'Açúcares \n[g]', 'Oligossacáridos \n[g]', 'Amido \n[g]',
       'Fibra  \n[g]', 'Proteínas \n[g]', 'Sal  \n[g]', 'Álcool \n[g]',
       'Água \n[g]', 'Ácidos orgânicos \n[g]', 'Colesterol \n[mg]',
       'Vitamina A  \n[µg]', 'Caroteno \n[µg]', 'Vitamina D \n[µg]',
       'alfa-tocoferol \n[mg]', 'Tiamina \n[mg]', 'Riboflavina \n[mg]',
       'Niacina \n[mg]', 'Equivalentes de niacina \n[mg]',
       'Triptofano/60 \n[mg]', 'Vitamina B6 \n[mg]', 'Vitamina B12 \n[µg]',
       'Vitamina C \n[mg]', 'Folatos \n[µg]', 'Cinza \n[g]', 'Sódio \n[mg]',
       'Potássio \n[mg]', 'Cálcio \n[mg]', 'Fósforo \n[mg]', 'Magnésio \n[mg]',
       'Ferro \n[mg]', 'Zinco \n[mg]'],
      dtype='object')

In [42]:
# translator = T(service_urls=['translate.googleapis.com'])
translator = T()
col = ['Nome do alimento', 'Nível 1', 'Nível 2', 'Nivel 3']

In [43]:
def translate(text):
  time.sleep(0.4)
  t = translator.translate(text, dest="en")
  return t.text

In [44]:
len(table)

1307

In [45]:
start = time.time()
print(table['Nome do alimento'][:6].apply(lambda x: translate(x)))
end = time.time()
print(f"Apply took {end-start:.3f} seconds")

1                 Avocado
2    Crystallized pumpkin
3             Raw pumpkin
4          Cooked cushion
5               Raw crash
6                 Saffron
Name: Nome do alimento, dtype: object
Apply took 3.523 seconds

In [46]:
table[col] = table[col].astype(str)

In [47]:
table[col].dtypes

Nome do alimento    object
Nível 1             object
Nível 2             object
Nivel 3             object
dtype: object

In [48]:
table['Nome do alimento'][:6].apply(lambda x: translate(x))

1                 Avocado
2    Crystallized pumpkin
3             Raw pumpkin
4          Cooked cushion
5               Raw crash
6                 Saffron
Name: Nome do alimento, dtype: object

In [49]:
table['Nome do alimento'] = table['Nome do alimento'].apply(lambda x: translate(x))

In [50]:
table['Nível 1'] = table['Nível 1'].apply(lambda x: translate(x))

In [51]:
table['Nível 2'] = table['Nível 2'].apply(lambda x: translate(x))

In [54]:
table['Nivel 3'] = table['Nivel 3'].apply(lambda x: translate(x))

In [56]:
table.head()

,Cod,Nome do alimento,Nível 1,Nível 2,Nivel 3,Energia\n[kcal],Energia\n[kJ],Lípidos\n[g],Ácidos gordos saturados\n[g],Ácidos gordos monoinsaturados \n[g],...,Vitamina C \n[mg],Folatos \n[µg],Cinza \n[g],Sódio \n[mg],Potássio \n[mg],Cálcio \n[mg],Fósforo \n[mg],Magnésio \n[mg],Ferro \n[mg],Zinco \n[mg]
1,624,Avocado,Fruits and products derived from fruits,Fruit used as fruit,"Various fruits with non -edible shell, large",114,470,10.5,2.2,6.5,...,3,11,0.75,15,330,4,36,21,0.3,0.3
2,625,Crystallized pumpkin,Hortical and Derivatives Products,Transformed or pickled vegetables and similar ...,Crystallized or sugar -conserved vegetables,293,1240,0.2,0.1,0,...,0,0,0.15,27,22,28,2,3,0.4,0.1
3,579,Raw pumpkin,Hortical and Derivatives Products,Horticultural fruits,Plant fruits,11,47,0.2,0.1,0,...,12,8,0.4,1,200,25,5,5,0.1,0.1
4,801,Cooked cushion,"Fish, shellfish, amphibians, reptiles and inve...",Fish (muscle),Sea fish,79,334,0.1,0,0,...,0,12,2,360,360,13,270,36,0.2,0.6
5,800,Raw crash,"Fish, shellfish, amphibians, reptiles and inve...",Fish (muscle),Sea fish,70,296,0.1,0,0,...,0,12,1.1,63,360,11,230,28,0.2,0.5

In [72]:
col_name = table.columns

for col in col_name:
    table.rename(columns={col:(translator.translate(col, dest="en")).text}, inplace=True)

In [96]:
table.columns = table.columns.str.replace("\n", '_', regex=False)
table.columns = table.columns.str.replace(" ", '_', regex=False)
table.columns = table.columns.str.replace("[", '', regex=False)
table.columns = table.columns.str.replace("]", '', regex=False)
table.columns = table.columns.str.replace("FIBRA", 'Fiber', regex=False)
table.columns = table.columns.str.replace('"', '', regex=False)
table.columns = table.columns.str.capitalize()
table.columns

Index(['Cod', 'Food_name', 'Level_1', 'Level_2', 'Level_3', 'Energy_kcal',
       'Energy_kg', 'Lipids_g', 'Saturated_fat_acids_g',
       'Monounsaturated_fatty_acids_g', 'Polynsaturated_fatty_acids_g',
       'Linoleic_acid_g', 'Trans_fat_acids_g', 'Carbohydrates_g', 'Sugars_g',
       'Oligoscarids_g', 'Aimido_g', 'Fiber_g', 'Proteins_g', 'Sal___g',
       'Alcohol_g', 'Water_g', 'Organic_acids_g', 'Colesterol__mg',
       'Vitamin_a_μg', 'Carotene_μg', 'Vitamin_d_μg', 'Alpha-tocoferol_mg',
       'Tiamina__mg', 'Riboflavina_mg', 'Niacina_mg', 'Niacin_equivalents_mg',
       'Triptofano/60__mg', 'Vitamin_bs_hopper', 'Vitamina_b1_μg',
       'Vitamina_c_mg', 'Folates_μg', 'Grey_g', 'Sodium_mg', 'Potassium_mg',
       'Calcium_mg', 'Phosphor_mg', 'Magnesium_mg', 'Ferro__mg', 'Zinco__mg'],
      dtype='object')

In [97]:
table.head(2)

,Cod,Food_name,Level_1,Level_2,Level_3,Energy_kcal,Energy_kg,Lipids_g,Saturated_fat_acids_g,Monounsaturated_fatty_acids_g,...,Vitamina_c_mg,Folates_μg,Grey_g,Sodium_mg,Potassium_mg,Calcium_mg,Phosphor_mg,Magnesium_mg,Ferro__mg,Zinco__mg
1,624,Avocado,Fruits and products derived from fruits,Fruit used as fruit,"Various fruits with non -edible shell, large",114,470,10.5,2.2,6.5,...,3,11,0.75,15,330,4,36,21,0.3,0.3
2,625,Crystallized pumpkin,Hortical and Derivatives Products,Transformed or pickled vegetables and similar ...,Crystallized or sugar -conserved vegetables,293,1240,0.2,0.1,0,...,0,0,0.15,27,22,28,2,3,0.4,0.1

In [98]:
table.to_csv('DataSets\insa_translated_table.csv', index=False)

## Issues with the translation

In [10]:
table_en = pd.read_csv('DataSets\insa_translated_table.csv')

In [49]:
table_en['Food_name'].replace('Wake up', 'Açorda', inplace=True)
table_en['Food_name'].replace('Alentejo', 'Açorda from Alentejo', inplace=True)
table_en['Food_name'].replace('Cod Sugar', 'Açorda with Cod', inplace=True)
table_en['Food_name'].replace('Seafood', 'Açorda with Seafood', inplace=True)
table_en['Food_name'].replace('Egg Açorda', 'Açorda with egg', inplace=True)

In [69]:

table_en['Food_name'].replace('Rice à Valenciana', 'Valenciana rice', inplace=True)
table_en['Food_name'].replace('Malandrinho Chicken Rice to Monsoon', 'Chicken Rice from Monção', inplace=True)
table_en['Food_name'].replace('INTEGRAL RICE CRU', 'Raw integral rice', inplace=True)
table_en['Food_name'].replace("Codfish to Brás", "Brás's Codfish", inplace=True)
table_en['Food_name'].replace("Codfish to Brás with olive oil", "Brás's Codfish with olive oil", inplace=True)
table_en['Food_name'].replace("Codfish to Brás with olive oil and olives", "Brás's Codfish with olive oil and olives", inplace=True)
table_en['Food_name'].replace("Cod to Gomes de Sá", "Gomes de Sá Cod", inplace=True)
table_en['Food_name'].replace("Cod to Gomes de Sá, with olive oil", "Gomes de Sá Cod with olive oil", inplace=True)
table_en['Food_name'].replace("Nipples", "maminha", inplace=True)
table_en['Food_name'].replace("Cooked to Portuguese with grain", "Portuguese stew with chickpea", inplace=True)
table_en['Food_name'].replace("Chocolate lightning", "chocolate Éclair", inplace=True)
table_en['Food_name'].replace("Golden Grilled", "grilled giltfish", inplace=True)
table_en['Food_name'].replace("Raw golden", "Raw giltfish", inplace=True)
table_en['Food_name'].replace("Cooked golden", "Boiled giltfish", inplace=True)
table_en['Food_name'].replace("Raw golden", "Raw giltfish", inplace=True)
table_en['Food_name'].replace("Endish raw", "Raw endive", inplace=True)

table_en['Food_name'][372] = 'Raw portuguese cabbage'
table_en['Food_name'][373] = 'Raw red cabbage'

C:\Users\inesa\AppData\Local\Temp\ipykernel_10608\3671175409.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table_en['Food_name'][372] = 'Raw portuguese cabbage'
C:\Users\inesa\AppData\Local\Temp\ipykernel_10608\3671175409.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table_en['Food_name'][373] = 'Raw red cabbage'
C:\Users\inesa\AppData\Local\Temp\ipykernel_10608\3671175409.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table_en['Food_name'][476] = "Portuguese's broad beans"

In [72]:
table_en['Food_name'][475] = "Portuguese's broad beans"
table_en['Food_name'][475] = "Raw broad beans"
table_en['Food_name'].replace("Raw fresh beans", "Raw fresh broad beans", inplace=True)

C:\Users\inesa\AppData\Local\Temp\ipykernel_10608\183920518.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table_en['Food_name'][475] = "Portuguese's broad beans"
C:\Users\inesa\AppData\Local\Temp\ipykernel_10608\183920518.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table_en['Food_name'][475] = "Raw broad beans"

In [73]:
display(table_pt.iloc[474:478,:])
display(table_en.iloc[474:478,:])

,Cod,Nome do alimento,Nível 1,Nível 2,Nivel 3,Energia\n[kcal],Energia\n[kJ],Lípidos\n[g],Ácidos gordos saturados\n[g],Ácidos gordos monoinsaturados \n[g],...,Vitamina C \n[mg],Folatos \n[µg],Cinza \n[g],Sódio \n[mg],Potássio \n[mg],Cálcio \n[mg],Fósforo \n[mg],Magnésio \n[mg],Ferro \n[mg],Zinco \n[mg]
475,347,Farinheira crua,Carne e produtos cárneos,Enchidos,Enchidos preservados ou parcialmente preservados,497,2060,41,14.5,16,...,0,6,2.8,960,140,25,70,18,1.6,0.7
476,1132,Favada à portuguesa,Pratos compostos,"Pratos, incl. refeições prontas a comer (exclu...","Pratos, excluindo pratos de massa ou arroz, s...",130,542,5.9,1.9,2.2,...,24.2,140,1.51,240,300,31,95,34,1.7,1.1
477,576,Favas frescas cozidas,"Leguminosas, frutos de casca rija, sementes ol...",Leguminosas,"Sementes de leguminosas frescas (feijão, ervil...",73,305,0.5,0.1,0.1,...,14,83,0.62,100,230,24,79,30,1,0.9
478,575,Favas frescas cruas,"Leguminosas, frutos de casca rija, sementes ol...",Leguminosas,"Sementes de leguminosas frescas (feijão, ervil...",80,338,0.5,0.1,0,...,23,150,0.84,7,270,25,87,32,1.2,1

,food_id,Food_name,Level_1,Level_2,Level_3,Energy_kcal,Energy_kg,Lipids_g,Saturated_fat_acids_g,Monounsaturated_fatty_acids_g,...,Vitamina_c_mg,Folates_μg,Grey_g,Sodium_mg,Potassium_mg,Calcium_mg,Phosphor_mg,Magnesium_mg,Ferro__mg,Zinco__mg
474,475,Raw farinheira,Meat and Meats,Sausage,Preserved or partially preserved sausages,497,2060,41.0,14.5,16.0,...,0.0,6.0,2.80,960.0,140.0,25.0,70,18.0,1.6,0.7
475,476,Raw broad beans,Compound dishes,"Dishes, inc.Meals ready to eat (excluding soup...","Dishes, excluding dishes of pasta or rice, san...",130,542,5.9,1.9,2.2,...,24.2,140.0,1.51,240.0,300.0,31.0,95,34.0,1.7,1.1
476,477,Portuguese's broad beans,"Legumes, rija bark fruits, oilseeds and spices",Legumes,"Seeds of fresh legumes (beans, peas etc.)",73,305,0.5,0.1,0.1,...,14.0,83.0,0.62,100.0,230.0,24.0,79,30.0,1.0,0.9
477,478,Raw fresh broad beans,"Legumes, rija bark fruits, oilseeds and spices",Legumes,"Seeds of fresh legumes (beans, peas etc.)",80,338,0.5,0.1,0.0,...,23.0,150.0,0.84,7.0,270.0,25.0,87,32.0,1.2,1.0

## Data Types, nulls and unicode characters (b'\x02\x00\x00\x00\x00\x00\x00\x00',) on Cod column

In [120]:
table_en.dtypes

food_id                          float64
Food_name                         object
Level_1                           object
Level_2                           object
Level_3                           object
Energy_kcal                      float64
Energy_kg                        float64
Lipids_g                         float64
Saturated_fat_acids_g            float64
Monounsaturated_fatty_acids_g    float64
Polynsaturated_fatty_acids_g     float64
Linoleic_acid_g                  float64
Trans_fat_acids_g                float64
Carbohydrates_g                  float64
Sugars_g                         float64
Oligoscarids_g                   float64
Aimido_g                         float64
Fiber_g                          float64
Proteins_g                       float64
Sal___g                          float64
Alcohol_g                        float64
Water_g                          float64
Organic_acids_g                  float64
Colesterol__mg                   float64
Vitamin_a_μg                     float64
Carotene_μg                      float64
Vitamin_d_μg                     float64
Alpha-tocoferol_mg               float64
Tiamina__mg                      float64
Riboflavina_mg                   float64
Niacina_mg                       float64
Niacin_equivalents_mg            float64
Triptofano/60__mg                float64
Vitamin_bs_hopper                float64
Vitamina_b1_μg                   float64
Vitamina_c_mg                    float64
Folates_μg                       float64
Grey_g                           float64
Sodium_mg                        float64
Potassium_mg                     float64
Calcium_mg                       float64
Phosphor_mg                      float64
Magnesium_mg                     float64
Ferro__mg                        float64
Zinco__mg                        float64
dtype: object

In [116]:
for columns in table_en.columns:
    if table_en[columns].dtype == 'int64':
        print (columns)

In [119]:
table_en['food_id'] = table_en['food_id'].astype(float)
table_en['Energy_kcal'] = table_en['Energy_kcal'].astype(float)
table_en['Energy_kg'] = table_en['Energy_kg'].astype(float)
table_en['Phosphor_mg'] = table_en['Phosphor_mg'].astype(float)

In [13]:
table_en.isnull().sum()

Cod                               0
Food_name                         0
Level_1                           0
Level_2                           0
Level_3                           0
Energy_kcal                       0
Energy_kg                         0
Lipids_g                          0
Saturated_fat_acids_g             1
Monounsaturated_fatty_acids_g     1
Polynsaturated_fatty_acids_g      0
Linoleic_acid_g                   0
Trans_fat_acids_g                 0
Carbohydrates_g                   0
Sugars_g                          0
Oligoscarids_g                    0
Aimido_g                          0
Fiber_g                           0
Proteins_g                        0
Sal___g                           0
Alcohol_g                         0
Water_g                           0
Organic_acids_g                   0
Colesterol__mg                    2
Vitamin_a_μg                     12
Carotene_μg                      13
Vitamin_d_μg                      1
Alpha-tocoferol_mg                0
Tiamina__mg                      12
Riboflavina_mg                    0
Niacina_mg                        0
Niacin_equivalents_mg             0
Triptofano/60__mg                 0
Vitamin_bs_hopper                 1
Vitamina_b1_μg                    0
Vitamina_c_mg                    14
Folates_μg                        0
Grey_g                            0
Sodium_mg                         1
Potassium_mg                      0
Calcium_mg                        1
Phosphor_mg                       0
Magnesium_mg                      0
Ferro__mg                         0
Zinco__mg                         0
dtype: int64

In [14]:
table_en.fillna(0, inplace=True)

In [15]:
table_en.isnull().sum()

Cod                              0
Food_name                        0
Level_1                          0
Level_2                          0
Level_3                          0
Energy_kcal                      0
Energy_kg                        0
Lipids_g                         0
Saturated_fat_acids_g            0
Monounsaturated_fatty_acids_g    0
Polynsaturated_fatty_acids_g     0
Linoleic_acid_g                  0
Trans_fat_acids_g                0
Carbohydrates_g                  0
Sugars_g                         0
Oligoscarids_g                   0
Aimido_g                         0
Fiber_g                          0
Proteins_g                       0
Sal___g                          0
Alcohol_g                        0
Water_g                          0
Organic_acids_g                  0
Colesterol__mg                   0
Vitamin_a_μg                     0
Carotene_μg                      0
Vitamin_d_μg                     0
Alpha-tocoferol_mg               0
Tiamina__mg                      0
Riboflavina_mg                   0
Niacina_mg                       0
Niacin_equivalents_mg            0
Triptofano/60__mg                0
Vitamin_bs_hopper                0
Vitamina_b1_μg                   0
Vitamina_c_mg                    0
Folates_μg                       0
Grey_g                           0
Sodium_mg                        0
Potassium_mg                     0
Calcium_mg                       0
Phosphor_mg                      0
Magnesium_mg                     0
Ferro__mg                        0
Zinco__mg                        0
dtype: int64

In [19]:
table_en['Cod'].sort_values(ascending=False)

613     2122000015
377     2122000014
113     2122000013
1065    2122000012
1064    2122000011
           ...
17               5
19               4
18               3
16               2
21               1
Name: Cod, Length: 1307, dtype: int64

In [34]:
table_en.drop(columns='Cod', inplace=True)
f_id_series = pd.Series([x for x in range(1,len(table_en)+1)], name='food_id')

In [111]:
table_en = pd.concat([f_id_series, table_en], axis=1)

In [121]:
table_en

,food_id,Food_name,Level_1,Level_2,Level_3,Energy_kcal,Energy_kg,Lipids_g,Saturated_fat_acids_g,Monounsaturated_fatty_acids_g,...,Vitamina_c_mg,Folates_μg,Grey_g,Sodium_mg,Potassium_mg,Calcium_mg,Phosphor_mg,Magnesium_mg,Ferro__mg,Zinco__mg
0,1.0,Avocado,Fruits and products derived from fruits,Fruit used as fruit,"Various fruits with non -edible shell, large",114.0,470.0,10.5,2.2,6.5,...,3.0,11.0,0.75,15.0,330.0,4.0,36.0,21.0,0.3,0.3
1,2.0,Crystallized pumpkin,Hortical and Derivatives Products,Transformed or pickled vegetables and similar ...,Crystallized or sugar -conserved vegetables,293.0,1240.0,0.2,0.1,0.0,...,0.0,0.0,0.15,27.0,22.0,28.0,2.0,3.0,0.4,0.1
2,3.0,Raw pumpkin,Hortical and Derivatives Products,Horticultural fruits,Plant fruits,11.0,47.0,0.2,0.1,0.0,...,12.0,8.0,0.40,1.0,200.0,25.0,5.0,5.0,0.1,0.1
3,4.0,Cooked cushion,"Fish, shellfish, amphibians, reptiles and inve...",Fish (muscle),Sea fish,79.0,334.0,0.1,0.0,0.0,...,0.0,12.0,2.00,360.0,360.0,13.0,270.0,36.0,0.2,0.6
4,5.0,Raw crash,"Fish, shellfish, amphibians, reptiles and inve...",Fish (muscle),Sea fish,70.0,296.0,0.1,0.0,0.0,...,0.0,12.0,1.10,63.0,360.0,11.0,230.0,28.0,0.2,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302,1303.0,Red mature wine,Alcoholic beverages,Wine and similar drinks,Wine,66.0,272.0,0.0,0.0,0.0,...,0.0,0.0,0.28,9.0,130.0,15.0,9.0,9.0,1.0,0.1
1303,1304.0,Rosé wine,Alcoholic beverages,Wine and similar drinks,Wine,72.0,299.0,0.0,0.0,0.0,...,0.0,0.0,0.28,7.0,91.0,14.0,15.0,10.0,1.0,0.1
1304,1305.0,White green wine,Alcoholic beverages,Wine and similar drinks,Wine,59.0,245.0,0.0,0.0,0.0,...,0.0,0.0,0.15,11.0,84.0,10.0,6.0,6.0,0.6,0.2
1305,1306.0,Red -green wine,Alcoholic beverages,Wine and similar drinks,Wine,57.0,237.0,0.0,0.0,0.0,...,0.0,0.0,0.22,15.0,110.0,13.0,8.0,7.0,1.0,0.1
1306,1307.0,"Wasabi, raw root","Legumes, rija bark fruits, oilseeds and spices",Spice,Root and Tuber Pesternity,100.0,422.0,0.6,0.2,0.2,...,58.5,34.0,1.71,21.0,530.0,110.0,80.0,58.0,0.9,1.2

In [118]:
table_en.to_csv('DataSets\insa_translated_table.csv', index=False)